---
title: "Publication-ready occurrence matrices with rWCVP"
author: "Matilda Brown"
date: "24/05/2022"
---
<!-- GENERATED BY vignettes/articles/precompile.R -->



The [World Checklist of Vascular Plants (WCVP)](https://wcvp.science.kew.org) provides distribution data for the > 340,000 vascular plant species known to science. This distribution data can be used to build occurrence matrices for checklists of plant species, which `rWCVP` can help with.


As well as `rWCVP`, well use the `tidyverse` packages for data manipulation and plotting and the `gt` package for formatting tables.


```r
library(rWCVP)
library(tidyverse)
library(gt)
```

In this example I use the pipe operator (`%>%`) and `dplyr` syntax - if these are unfamiliar I suggest checking out https://dplyr.tidyverse.org/ and some of the help pages therein. 

Now, let's get started! 

## Finding an example group

For this example, we don't have a particular area or group of plants that we want to examine, but this gives us a chance to showcase one of other the functions in `rWCVP`! 

We want a group of species that is a) not too large and b) distributed across a few WGSRPD Level 3 Areas. Brazil has good potential because it has five Level 3 Areas (a good number for this purpose because the table will fit on a portrait-oriented page). Let's see if there are some nice-sized example genera, using the `wcvp_summary` function: 

```r
wcvp_summary(taxon="Myrtaceae", taxon_rank="family", area=get_wgsrpd3_codes("Brazil"), 
              grouping_var = "genus") %>% 
  wcvp_summary_gt()
```

<!--html_preserve--><div id="vkzfpcszkz" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#vkzfpcszkz .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#vkzfpcszkz .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vkzfpcszkz .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#vkzfpcszkz .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#vkzfpcszkz .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vkzfpcszkz .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#vkzfpcszkz .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#vkzfpcszkz .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#vkzfpcszkz .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#vkzfpcszkz .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#vkzfpcszkz .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#vkzfpcszkz .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#vkzfpcszkz .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#vkzfpcszkz .gt_from_md > :first-child {
  margin-top: 0;
}

#vkzfpcszkz .gt_from_md > :last-child {
  margin-bottom: 0;
}

#vkzfpcszkz .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#vkzfpcszkz .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#vkzfpcszkz .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#vkzfpcszkz .gt_row_group_first td {
  border-top-width: 2px;
}

#vkzfpcszkz .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vkzfpcszkz .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#vkzfpcszkz .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#vkzfpcszkz .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vkzfpcszkz .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#vkzfpcszkz .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#vkzfpcszkz .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#vkzfpcszkz .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#vkzfpcszkz .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vkzfpcszkz .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vkzfpcszkz .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#vkzfpcszkz .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#vkzfpcszkz .gt_left {
  text-align: left;
}

#vkzfpcszkz .gt_center {
  text-align: center;
}

#vkzfpcszkz .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#vkzfpcszkz .gt_font_normal {
  font-weight: normal;
}

#vkzfpcszkz .gt_font_bold {
  font-weight: bold;
}

#vkzfpcszkz .gt_font_italic {
  font-style: italic;
}

#vkzfpcszkz .gt_super {
  font-size: 65%;
}

#vkzfpcszkz .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#vkzfpcszkz .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#vkzfpcszkz .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#vkzfpcszkz .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#vkzfpcszkz .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#vkzfpcszkz .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal" style><b> Myrtaceae of Brazil </b></th>
    </tr>
    <tr>
      <th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Total number of species: 1127<br>Number of regionally endemic species: 878</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Genus</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Native</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Endemic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Introduced</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Extinct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Total</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Accara</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr><td class="gt_row gt_left">Algrizea</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">2</td></tr>
    <tr><td class="gt_row gt_left">Blepharocalyx</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">3</td></tr>
    <tr><td class="gt_row gt_left">Calycolpus</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">8</td></tr>
    <tr><td class="gt_row gt_left">Calycorectes</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">9</td></tr>
    <tr><td class="gt_row gt_left">Campomanesia</td>
<td class="gt_row gt_right">41</td>
<td class="gt_row gt_right">31</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right" style="font-weight: bold;">42</td></tr>
    <tr><td class="gt_row gt_left">Curitiba</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr><td class="gt_row gt_left">Eugenia</td>
<td class="gt_row gt_right">430</td>
<td class="gt_row gt_right">338</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">431</td></tr>
    <tr><td class="gt_row gt_left">Feijoa</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr><td class="gt_row gt_left">Myrceugenia</td>
<td class="gt_row gt_right">34</td>
<td class="gt_row gt_right">30</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">34</td></tr>
    <tr><td class="gt_row gt_left">Myrcia</td>
<td class="gt_row gt_right">440</td>
<td class="gt_row gt_right">351</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right" style="font-weight: bold;">441</td></tr>
    <tr><td class="gt_row gt_left">Myrcianthes</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">7</td></tr>
    <tr><td class="gt_row gt_left">Myrciaria</td>
<td class="gt_row gt_right">23</td>
<td class="gt_row gt_right">15</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">23</td></tr>
    <tr><td class="gt_row gt_left">Myrrhinium</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr><td class="gt_row gt_left">Neomitranthes</td>
<td class="gt_row gt_right">13</td>
<td class="gt_row gt_right">13</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">13</td></tr>
    <tr><td class="gt_row gt_left">Pimenta</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr><td class="gt_row gt_left">Plinia</td>
<td class="gt_row gt_right">41</td>
<td class="gt_row gt_right">35</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">41</td></tr>
    <tr><td class="gt_row gt_left">Psidium</td>
<td class="gt_row gt_right">57</td>
<td class="gt_row gt_right">36</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">57</td></tr>
    <tr><td class="gt_row gt_left">Siphoneugena</td>
<td class="gt_row gt_right">10</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">10</td></tr>
    <tr><td class="gt_row gt_left">Syzygium</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->
*Calycolpus* looks nice and tidy - let's see how the 8 species are distributed across the 5 areas. We can use the same function, but limit our taxon and change our grouping variable to area.

```r
wcvp_summary(taxon="Calycolpus", taxon_rank="genus", area=get_wgsrpd3_codes("Brazil"),
              grouping_var = "area_code_l3") %>% 
  wcvp_summary_gt()
```

<!--html_preserve--><div id="awhtzcisff" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#awhtzcisff .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#awhtzcisff .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#awhtzcisff .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#awhtzcisff .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#awhtzcisff .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#awhtzcisff .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#awhtzcisff .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#awhtzcisff .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#awhtzcisff .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#awhtzcisff .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#awhtzcisff .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#awhtzcisff .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#awhtzcisff .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#awhtzcisff .gt_from_md > :first-child {
  margin-top: 0;
}

#awhtzcisff .gt_from_md > :last-child {
  margin-bottom: 0;
}

#awhtzcisff .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#awhtzcisff .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#awhtzcisff .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#awhtzcisff .gt_row_group_first td {
  border-top-width: 2px;
}

#awhtzcisff .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#awhtzcisff .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#awhtzcisff .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#awhtzcisff .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#awhtzcisff .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#awhtzcisff .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#awhtzcisff .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#awhtzcisff .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#awhtzcisff .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#awhtzcisff .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#awhtzcisff .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#awhtzcisff .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#awhtzcisff .gt_left {
  text-align: left;
}

#awhtzcisff .gt_center {
  text-align: center;
}

#awhtzcisff .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#awhtzcisff .gt_font_normal {
  font-weight: normal;
}

#awhtzcisff .gt_font_bold {
  font-weight: bold;
}

#awhtzcisff .gt_font_italic {
  font-style: italic;
}

#awhtzcisff .gt_super {
  font-size: 65%;
}

#awhtzcisff .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#awhtzcisff .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#awhtzcisff .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#awhtzcisff .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#awhtzcisff .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#awhtzcisff .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal" style><b> Calycolpus of Brazil </b></th>
    </tr>
    <tr>
      <th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Total number of species: 8<br>Number of regionally endemic species: 4</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Native</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Endemic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Introduced</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Extinct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Total</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZE</td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">3</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZL</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">1</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZN</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">5</td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->
Hmm, maybe a bit too small - it only occurs in 3 of the 5 regions. What about *Myrciaria*? 


```r
wcvp_summary(taxon="Myrciaria", taxon_rank="genus", area=get_wgsrpd3_codes("Brazil"), 
              grouping_var="area_code_l3") %>% 
  wcvp_summary_gt()
```

<!--html_preserve--><div id="cpwbqruspn" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#cpwbqruspn .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#cpwbqruspn .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cpwbqruspn .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#cpwbqruspn .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#cpwbqruspn .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cpwbqruspn .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#cpwbqruspn .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#cpwbqruspn .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#cpwbqruspn .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#cpwbqruspn .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#cpwbqruspn .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#cpwbqruspn .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#cpwbqruspn .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#cpwbqruspn .gt_from_md > :first-child {
  margin-top: 0;
}

#cpwbqruspn .gt_from_md > :last-child {
  margin-bottom: 0;
}

#cpwbqruspn .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#cpwbqruspn .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#cpwbqruspn .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#cpwbqruspn .gt_row_group_first td {
  border-top-width: 2px;
}

#cpwbqruspn .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cpwbqruspn .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#cpwbqruspn .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#cpwbqruspn .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cpwbqruspn .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#cpwbqruspn .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#cpwbqruspn .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#cpwbqruspn .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#cpwbqruspn .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cpwbqruspn .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cpwbqruspn .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#cpwbqruspn .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#cpwbqruspn .gt_left {
  text-align: left;
}

#cpwbqruspn .gt_center {
  text-align: center;
}

#cpwbqruspn .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#cpwbqruspn .gt_font_normal {
  font-weight: normal;
}

#cpwbqruspn .gt_font_bold {
  font-weight: bold;
}

#cpwbqruspn .gt_font_italic {
  font-style: italic;
}

#cpwbqruspn .gt_super {
  font-size: 65%;
}

#cpwbqruspn .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#cpwbqruspn .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#cpwbqruspn .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#cpwbqruspn .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#cpwbqruspn .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#cpwbqruspn .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal" style><b> Myrciaria of Brazil </b></th>
    </tr>
    <tr>
      <th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Total number of species: 23<br>Number of regionally endemic species: 15</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Native</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Endemic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Introduced</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Extinct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Total</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZC</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">6</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZE</td>
<td class="gt_row gt_right">13</td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">13</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZL</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right">4</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">16</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZN</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">6</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">BZS</td>
<td class="gt_row gt_right">5</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">6</td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->

Perfect! 23 species (rows) won't take up too much space, and there are enough occurrences to make it interesting. 

## Generating and formatting the occurrence matrix
Generating an occurrence matrix for this genus is as simple as using the `generate_occurence_matrix` function.  


```r
m <- wcvp_occ_mat(taxon="Myrciaria", taxon_rank="genus", 
                                area=get_wgsrpd3_codes("Brazil"))
m
#> # A tibble: 23 x 7
#>    plant_name_id taxon_name             BZC   BZE   BZL   BZN   BZS
#>            <dbl> <chr>                <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1        473796 Myrciaria alagoana       0     1     0     0     0
#>  2        534878 Myrciaria alta           0     0     1     0     0
#>  3        534776 Myrciaria cambuca        0     1     1     0     0
#>  4        131799 Myrciaria cordata        0     0     0     1     0
#>  5        131802 Myrciaria cuspidata      1     1     1     0     1
#>  6        131803 Myrciaria delicatula     1     0     1     0     1
#>  7        131806 Myrciaria disticha       0     1     1     0     0
#>  8        131810 Myrciaria dubia          1     0     0     1     0
#>  9        491614 Myrciaria evanida        0     0     1     0     0
#> 10        131814 Myrciaria ferruginea     0     1     1     0     0
#> # ... with 13 more rows
```

It's OK, but we can make it much prettier using the `gt` package.
Let's do the following: 

* remove the WCVP ID column
* change taxon_id to 'Species'
* make species names italic
* bold the column titles
* reduce the space around the text and make font size 12
* remove the internal borders
* change the 1s and 0s into X and blank


```r
m_gt <- m %>% 
  select(-plant_name_id) %>% #remove ID col
  gt() %>% 
  cols_label(
    taxon_name = "Species"
  ) %>% 
  #make species names italic
        tab_style(
        style=cell_text(style="italic"),
        locations = cells_body(
          columns= taxon_name
        )
      ) %>% 
  tab_options(
    # some nice formatting
        column_labels.font.weight = "bold",
        data_row.padding = px(1),
        table.font.size = 12,
        table_body.hlines.color = "transparent",
        ) %>%
  # change the zeroes into blanks
      text_transform(
        locations = cells_body(),
        fn = function(x){
          ifelse(x == 0, "", x)
        }
      ) %>% 
  # change the 1s into X
        text_transform(
        locations = cells_body(),
        fn = function(x){
          ifelse(x == 1, "X", x)
        }
      )
m_gt
```

<!--html_preserve--><div id="naypkdozxr" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#naypkdozxr .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#naypkdozxr .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#naypkdozxr .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#naypkdozxr .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#naypkdozxr .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#naypkdozxr .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#naypkdozxr .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#naypkdozxr .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#naypkdozxr .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#naypkdozxr .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#naypkdozxr .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#naypkdozxr .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#naypkdozxr .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#naypkdozxr .gt_from_md > :first-child {
  margin-top: 0;
}

#naypkdozxr .gt_from_md > :last-child {
  margin-bottom: 0;
}

#naypkdozxr .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#naypkdozxr .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#naypkdozxr .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#naypkdozxr .gt_row_group_first td {
  border-top-width: 2px;
}

#naypkdozxr .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#naypkdozxr .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#naypkdozxr .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#naypkdozxr .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#naypkdozxr .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#naypkdozxr .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#naypkdozxr .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#naypkdozxr .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#naypkdozxr .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#naypkdozxr .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#naypkdozxr .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#naypkdozxr .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#naypkdozxr .gt_left {
  text-align: left;
}

#naypkdozxr .gt_center {
  text-align: center;
}

#naypkdozxr .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#naypkdozxr .gt_font_normal {
  font-weight: normal;
}

#naypkdozxr .gt_font_bold {
  font-weight: bold;
}

#naypkdozxr .gt_font_italic {
  font-style: italic;
}

#naypkdozxr .gt_super {
  font-size: 65%;
}

#naypkdozxr .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#naypkdozxr .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#naypkdozxr .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#naypkdozxr .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#naypkdozxr .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#naypkdozxr .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Species</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BZC</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BZE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BZL</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BZN</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BZS</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria alagoana</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria alta</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria cambuca</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria cordata</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria cuspidata</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria delicatula</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria disticha</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria dubia</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria evanida</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria ferruginea</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria floribunda</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria glanduliflora</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria glazioviana</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria glomerata</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria guaquiea</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria pallida</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria pilosa</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria plinioides</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria rojasii</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria strigipes</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria tenella</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria una</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Myrciaria vismeifolia</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->

Much nicer! We can save this `gt` table as an HTML table or as a picture. If we plan on making a few more tables, we can save space by saving our table style as a theme (see https://themockup.blog/posts/2020-09-26-functions-and-themes-for-gt-tables/ for more details on this)


```r
occ_mat_theme <- function(x){
  x %>% cols_label(
    taxon_name = "Species"
  ) %>% 
  #make species names italic
        tab_style(
        style=cell_text(style="italic"),
        locations = cells_body(
          columns= taxon_name
        )
      ) %>% 
  tab_options(
    # some nice formatting
        column_labels.font.weight = "bold",
        data_row.padding = px(1),
        table.font.size = 12,
        table_body.hlines.color = "transparent",
        ) %>%
  # change the zeroes into blanks
      text_transform(
        locations = cells_body(),
        fn = function(x){
          ifelse(x == 0, "", x)
        }
      ) %>% 
  # change the 1s into X
        text_transform(
        locations = cells_body(),
        fn = function(x){
          ifelse(x == 1, "X", x)
        }
      )
}
```

The biggest issue with `gt()` is that it doesn't support Word - for exporting directly to a docx file, check out `flextable` (https://ardata-fr.github.io/flextable-book/).
### Including or excluding occurrence types
What if we only want to know about native or introduced species? This function has the option to filter for one or the other. Brazilian *Myrciaria* doesn't look very interesting on that front (we can see from the summary table that only one species is introduced), so let's look at a more invasive group - *Poa* in Northern Europe (Level 2 Region). 


```r
wcvp_summary(taxon="Poa", taxon_rank="genus", area=get_wgsrpd3_codes("Northern Europe"), 
              grouping_var = "area_code_l3") %>% 
  wcvp_summary_gt()
```

<!--html_preserve--><div id="afjgzbbvlb" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#afjgzbbvlb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#afjgzbbvlb .gt_heading {
  background-color: #FFFFFF;
  text-align: left;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#afjgzbbvlb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#afjgzbbvlb .gt_subtitle {
  color: #333333;
  font-size: 12px;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#afjgzbbvlb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#afjgzbbvlb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#afjgzbbvlb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#afjgzbbvlb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#afjgzbbvlb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#afjgzbbvlb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#afjgzbbvlb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#afjgzbbvlb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#afjgzbbvlb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#afjgzbbvlb .gt_from_md > :first-child {
  margin-top: 0;
}

#afjgzbbvlb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#afjgzbbvlb .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#afjgzbbvlb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#afjgzbbvlb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#afjgzbbvlb .gt_row_group_first td {
  border-top-width: 2px;
}

#afjgzbbvlb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#afjgzbbvlb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#afjgzbbvlb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#afjgzbbvlb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#afjgzbbvlb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#afjgzbbvlb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#afjgzbbvlb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#afjgzbbvlb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#afjgzbbvlb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#afjgzbbvlb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#afjgzbbvlb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#afjgzbbvlb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#afjgzbbvlb .gt_left {
  text-align: left;
}

#afjgzbbvlb .gt_center {
  text-align: center;
}

#afjgzbbvlb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#afjgzbbvlb .gt_font_normal {
  font-weight: normal;
}

#afjgzbbvlb .gt_font_bold {
  font-weight: bold;
}

#afjgzbbvlb .gt_font_italic {
  font-style: italic;
}

#afjgzbbvlb .gt_super {
  font-size: 65%;
}

#afjgzbbvlb .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#afjgzbbvlb .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#afjgzbbvlb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#afjgzbbvlb .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#afjgzbbvlb .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#afjgzbbvlb .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="6" class="gt_heading gt_title gt_font_normal" style><b> Poa of Northern Europe </b></th>
    </tr>
    <tr>
      <th colspan="6" class="gt_heading gt_subtitle gt_font_normal gt_bottom_border" style>Total number of species: 23<br>Number of regionally endemic species: 0</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1"></th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Native</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Endemic</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Introduced</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Extinct</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">Total</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">DEN</td>
<td class="gt_row gt_right">11</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">12</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">FIN</td>
<td class="gt_row gt_right">16</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">17</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">FOR</td>
<td class="gt_row gt_right">8</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">8</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">GRB</td>
<td class="gt_row gt_right">12</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">3</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">15</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">ICE</td>
<td class="gt_row gt_right">9</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">11</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">IRE</td>
<td class="gt_row gt_right">6</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">2</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">8</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">NOR</td>
<td class="gt_row gt_right">17</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">18</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">SVA</td>
<td class="gt_row gt_right">7</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">7</td></tr>
    <tr class="gt_row_group_first"><td rowspan="1" class="gt_row gt_right gt_stub_row_group" style="text-align: left;">SWE</td>
<td class="gt_row gt_right">17</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">1</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right" style="font-weight: bold;">18</td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->
A few more there to work with. First, let's look at the native species only:

```r
m <- wcvp_occ_mat(taxon="Poa", taxon_rank="genus",
                                area=get_wgsrpd3_codes("Northern Europe"), 
                                introduced=FALSE, extinct=FALSE, 
                                location_doubtful=FALSE)
m
#> # A tibble: 20 x 11
#>    plant_name_id taxon_name         DEN   FIN   FOR   GRB   ICE   IRE   NOR   SVA   SWE
#>            <dbl> <chr>            <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl> <dbl>
#>  1        435004 Poa abbreviata       0     0     0     0     0     0     0     1     0
#>  2        435078 Poa alpigena         0     1     1     0     1     0     1     1     1
#>  3        435085 Poa alpina           0     1     1     1     1     1     1     1     1
#>  4        435167 Poa angustifolia     1     1     0     1     0     0     1     0     1
#>  5        435194 Poa annua            1     1     1     1     1     1     1     0     1
#>  6        435235 Poa arctica          0     1     0     0     0     0     1     1     1
#>  7        435458 Poa bulbosa          1     1     0     1     0     0     1     0     1
#>  8        435622 Poa compressa        1     1     0     0     0     0     1     0     1
#>  9        435932 Poa flexuosa         0     0     0     1     1     0     1     0     1
#> 10        435996 Poa glauca           0     1     1     1     1     0     1     1     1
#> 11        436089 Poa hartzii          0     0     0     0     0     0     0     1     0
#> 12        436146 Poa humilis          1     1     1     1     1     1     1     0     1
#> 13        436189 Poa infirma          0     0     0     1     0     0     0     0     0
#> 14        436383 Poa lindebergii      0     1     0     0     0     0     1     0     1
#> 15        436600 Poa nemoralis        1     1     1     1     1     1     1     0     1
#> 16        436739 Poa palustris        1     1     0     1     0     0     1     0     1
#> 17        436906 Poa pratensis        1     1     1     1     1     1     1     1     1
#> 18        437092 Poa remota           1     1     0     0     0     0     1     0     1
#> 19        437424 Poa supina           1     1     0     0     0     0     1     0     1
#> 20        437547 Poa trivialis        1     1     1     1     1     1     1     0     1
```
We can format this matrix just like we did above, but let's skip that and go straight to introduced species only. We're doing all the same formatting as before, but also adding a heading - the `html` function makes it possiible to italicise our genus name and everything!


```r
m <- wcvp_occ_mat(taxon="Poa", taxon_rank="genus",
                                area=get_wgsrpd3_codes("Northern Europe"), 
                                native=FALSE,
                                introduced=TRUE, extinct=FALSE, 
                                location_doubtful = FALSE)
m %>% 
  select(-plant_name_id) %>% #remove ID col
  gt() %>% 
  occ_mat_theme() %>%  #the theme we defined above
  #add a header
  tab_header(title=html("Introduced <em>Poa</em> species in Northern Europe")) 
```

<!--html_preserve--><div id="swbsqpbyyc" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#swbsqpbyyc .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#swbsqpbyyc .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#swbsqpbyyc .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#swbsqpbyyc .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#swbsqpbyyc .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#swbsqpbyyc .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#swbsqpbyyc .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#swbsqpbyyc .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#swbsqpbyyc .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#swbsqpbyyc .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#swbsqpbyyc .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#swbsqpbyyc .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#swbsqpbyyc .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#swbsqpbyyc .gt_from_md > :first-child {
  margin-top: 0;
}

#swbsqpbyyc .gt_from_md > :last-child {
  margin-bottom: 0;
}

#swbsqpbyyc .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#swbsqpbyyc .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#swbsqpbyyc .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#swbsqpbyyc .gt_row_group_first td {
  border-top-width: 2px;
}

#swbsqpbyyc .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#swbsqpbyyc .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#swbsqpbyyc .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#swbsqpbyyc .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#swbsqpbyyc .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#swbsqpbyyc .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#swbsqpbyyc .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#swbsqpbyyc .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#swbsqpbyyc .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#swbsqpbyyc .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#swbsqpbyyc .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#swbsqpbyyc .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#swbsqpbyyc .gt_left {
  text-align: left;
}

#swbsqpbyyc .gt_center {
  text-align: center;
}

#swbsqpbyyc .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#swbsqpbyyc .gt_font_normal {
  font-weight: normal;
}

#swbsqpbyyc .gt_font_bold {
  font-weight: bold;
}

#swbsqpbyyc .gt_font_italic {
  font-style: italic;
}

#swbsqpbyyc .gt_super {
  font-size: 65%;
}

#swbsqpbyyc .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#swbsqpbyyc .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#swbsqpbyyc .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#swbsqpbyyc .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#swbsqpbyyc .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#swbsqpbyyc .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="10" class="gt_heading gt_title gt_font_normal gt_bottom_border" style>Introduced <em>Poa</em> species in Northern Europe</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Species</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">DEN</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">FIN</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">FOR</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">GRB</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">ICE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">IRE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">NOR</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">SVA</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">SWE</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa angustifolia</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa chaixii</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa compressa</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa flabellata</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa palustris</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Poa persica</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->

## Bonus: adding a country spanner
Tables created with `gt` are extremely flexible - let's say we want to look at occurrences across the US-Canadian border:

```r
m <- wcvp_occ_mat("Fritillaria", "genus", 
                                area=c("WAS", "ORE", "IDA","MNT", "ABT", "BRC"))


m_gt <- m %>% 
  select(-plant_name_id) %>% #remove ID col
  gt() %>% 
  occ_mat_theme() %>%  #the theme we defined above
  #add a header
  tab_header(title=html("<em>Fritillaria</em> species in Northwest USA and Southwest Canada")) 
m_gt
```

<!--html_preserve--><div id="kjhzhtkesb" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#kjhzhtkesb .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#kjhzhtkesb .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kjhzhtkesb .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#kjhzhtkesb .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#kjhzhtkesb .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kjhzhtkesb .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#kjhzhtkesb .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#kjhzhtkesb .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#kjhzhtkesb .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#kjhzhtkesb .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#kjhzhtkesb .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#kjhzhtkesb .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#kjhzhtkesb .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#kjhzhtkesb .gt_from_md > :first-child {
  margin-top: 0;
}

#kjhzhtkesb .gt_from_md > :last-child {
  margin-bottom: 0;
}

#kjhzhtkesb .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#kjhzhtkesb .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#kjhzhtkesb .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#kjhzhtkesb .gt_row_group_first td {
  border-top-width: 2px;
}

#kjhzhtkesb .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kjhzhtkesb .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#kjhzhtkesb .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#kjhzhtkesb .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kjhzhtkesb .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#kjhzhtkesb .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#kjhzhtkesb .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#kjhzhtkesb .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#kjhzhtkesb .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kjhzhtkesb .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kjhzhtkesb .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#kjhzhtkesb .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#kjhzhtkesb .gt_left {
  text-align: left;
}

#kjhzhtkesb .gt_center {
  text-align: center;
}

#kjhzhtkesb .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#kjhzhtkesb .gt_font_normal {
  font-weight: normal;
}

#kjhzhtkesb .gt_font_bold {
  font-weight: bold;
}

#kjhzhtkesb .gt_font_italic {
  font-style: italic;
}

#kjhzhtkesb .gt_super {
  font-size: 65%;
}

#kjhzhtkesb .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#kjhzhtkesb .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#kjhzhtkesb .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#kjhzhtkesb .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#kjhzhtkesb .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#kjhzhtkesb .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="7" class="gt_heading gt_title gt_font_normal gt_bottom_border" style><em>Fritillaria</em> species in Northwest USA and Southwest Canada</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">Species</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">ABT</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BRC</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">IDA</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">MNT</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">ORE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">WAS</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria affinis</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria atropurpurea</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria camschatcensis</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria eastwoodiae</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria gentneri</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria glauca</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria pudica</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria purdyi</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria recurva</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->

It would be really useful to know which of those codes are in the US and which are in Canada. We could use the data included in `rWCVP` to create a key.

```r
wgsrpd_mapping %>% 
  filter(LEVEL3_COD %in% c("WAS", "ORE", "IDA","MNT", "ABT", "BRC")) %>% 
  select(LEVEL3_NAM, LEVEL3_COD, COUNTRY) %>% 
  gt() %>% 
  #some formatting
  tab_options(
        column_labels.font.weight = "bold",
        data_row.padding = px(1),
        table.font.size = 12,
        table_body.hlines.color = "transparent",
        )
```

<!--html_preserve--><div id="nyqclhqzvd" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#nyqclhqzvd .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#nyqclhqzvd .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nyqclhqzvd .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#nyqclhqzvd .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#nyqclhqzvd .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nyqclhqzvd .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#nyqclhqzvd .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#nyqclhqzvd .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#nyqclhqzvd .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#nyqclhqzvd .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#nyqclhqzvd .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#nyqclhqzvd .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#nyqclhqzvd .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#nyqclhqzvd .gt_from_md > :first-child {
  margin-top: 0;
}

#nyqclhqzvd .gt_from_md > :last-child {
  margin-bottom: 0;
}

#nyqclhqzvd .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#nyqclhqzvd .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#nyqclhqzvd .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#nyqclhqzvd .gt_row_group_first td {
  border-top-width: 2px;
}

#nyqclhqzvd .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nyqclhqzvd .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#nyqclhqzvd .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#nyqclhqzvd .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nyqclhqzvd .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#nyqclhqzvd .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#nyqclhqzvd .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#nyqclhqzvd .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#nyqclhqzvd .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nyqclhqzvd .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nyqclhqzvd .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#nyqclhqzvd .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#nyqclhqzvd .gt_left {
  text-align: left;
}

#nyqclhqzvd .gt_center {
  text-align: center;
}

#nyqclhqzvd .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#nyqclhqzvd .gt_font_normal {
  font-weight: normal;
}

#nyqclhqzvd .gt_font_bold {
  font-weight: bold;
}

#nyqclhqzvd .gt_font_italic {
  font-style: italic;
}

#nyqclhqzvd .gt_super {
  font-size: 65%;
}

#nyqclhqzvd .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#nyqclhqzvd .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#nyqclhqzvd .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#nyqclhqzvd .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#nyqclhqzvd .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#nyqclhqzvd .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">LEVEL3_NAM</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">LEVEL3_COD</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1">COUNTRY</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left">Alberta</td>
<td class="gt_row gt_left">ABT</td>
<td class="gt_row gt_left">Canada</td></tr>
    <tr><td class="gt_row gt_left">British Columbia</td>
<td class="gt_row gt_left">BRC</td>
<td class="gt_row gt_left">Canada</td></tr>
    <tr><td class="gt_row gt_left">Idaho</td>
<td class="gt_row gt_left">IDA</td>
<td class="gt_row gt_left">United States</td></tr>
    <tr><td class="gt_row gt_left">Montana</td>
<td class="gt_row gt_left">MNT</td>
<td class="gt_row gt_left">United States</td></tr>
    <tr><td class="gt_row gt_left">Oregon</td>
<td class="gt_row gt_left">ORE</td>
<td class="gt_row gt_left">United States</td></tr>
    <tr><td class="gt_row gt_left">Washington</td>
<td class="gt_row gt_left">WAS</td>
<td class="gt_row gt_left">United States</td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->
It would really be nicer to have it on the occurrence matrix though. Enter `tab_spanner()`:

```r
m_gt %>% 
  tab_spanner(label="United States",
              columns = c(IDA, MNT, ORE, WAS)) %>% 
  tab_spanner(label="Canada",
              columns=c(ABT, BRC)) 
```

<!--html_preserve--><div id="lpzwjsibiv" style="overflow-x:auto;overflow-y:auto;width:auto;height:auto;">
<style>html {
  font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Helvetica Neue', 'Fira Sans', 'Droid Sans', Arial, sans-serif;
}

#lpzwjsibiv .gt_table {
  display: table;
  border-collapse: collapse;
  margin-left: auto;
  margin-right: auto;
  color: #333333;
  font-size: 12px;
  font-weight: normal;
  font-style: normal;
  background-color: #FFFFFF;
  width: auto;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #A8A8A8;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #A8A8A8;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
}

#lpzwjsibiv .gt_heading {
  background-color: #FFFFFF;
  text-align: center;
  border-bottom-color: #FFFFFF;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lpzwjsibiv .gt_title {
  color: #333333;
  font-size: 125%;
  font-weight: initial;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-color: #FFFFFF;
  border-bottom-width: 0;
}

#lpzwjsibiv .gt_subtitle {
  color: #333333;
  font-size: 85%;
  font-weight: initial;
  padding-top: 0;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-color: #FFFFFF;
  border-top-width: 0;
}

#lpzwjsibiv .gt_bottom_border {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lpzwjsibiv .gt_col_headings {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
}

#lpzwjsibiv .gt_col_heading {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 6px;
  padding-left: 5px;
  padding-right: 5px;
  overflow-x: hidden;
}

#lpzwjsibiv .gt_column_spanner_outer {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: bold;
  text-transform: inherit;
  padding-top: 0;
  padding-bottom: 0;
  padding-left: 4px;
  padding-right: 4px;
}

#lpzwjsibiv .gt_column_spanner_outer:first-child {
  padding-left: 0;
}

#lpzwjsibiv .gt_column_spanner_outer:last-child {
  padding-right: 0;
}

#lpzwjsibiv .gt_column_spanner {
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: bottom;
  padding-top: 5px;
  padding-bottom: 5px;
  overflow-x: hidden;
  display: inline-block;
  width: 100%;
}

#lpzwjsibiv .gt_group_heading {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
}

#lpzwjsibiv .gt_empty_group_heading {
  padding: 0.5px;
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  vertical-align: middle;
}

#lpzwjsibiv .gt_from_md > :first-child {
  margin-top: 0;
}

#lpzwjsibiv .gt_from_md > :last-child {
  margin-bottom: 0;
}

#lpzwjsibiv .gt_row {
  padding-top: 1px;
  padding-bottom: 1px;
  padding-left: 5px;
  padding-right: 5px;
  margin: 10px;
  border-top-style: solid;
  border-top-width: 1px;
  border-top-color: rgba(255, 255, 255, 0);
  border-left-style: none;
  border-left-width: 1px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 1px;
  border-right-color: #D3D3D3;
  vertical-align: middle;
  overflow-x: hidden;
}

#lpzwjsibiv .gt_stub {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
}

#lpzwjsibiv .gt_stub_row_group {
  color: #333333;
  background-color: #FFFFFF;
  font-size: 100%;
  font-weight: initial;
  text-transform: inherit;
  border-right-style: solid;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
  padding-left: 5px;
  padding-right: 5px;
  vertical-align: top;
}

#lpzwjsibiv .gt_row_group_first td {
  border-top-width: 2px;
}

#lpzwjsibiv .gt_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lpzwjsibiv .gt_first_summary_row {
  border-top-style: solid;
  border-top-color: #D3D3D3;
}

#lpzwjsibiv .gt_first_summary_row.thick {
  border-top-width: 2px;
}

#lpzwjsibiv .gt_last_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lpzwjsibiv .gt_grand_summary_row {
  color: #333333;
  background-color: #FFFFFF;
  text-transform: inherit;
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
}

#lpzwjsibiv .gt_first_grand_summary_row {
  padding-top: 8px;
  padding-bottom: 8px;
  padding-left: 5px;
  padding-right: 5px;
  border-top-style: double;
  border-top-width: 6px;
  border-top-color: #D3D3D3;
}

#lpzwjsibiv .gt_striped {
  background-color: rgba(128, 128, 128, 0.05);
}

#lpzwjsibiv .gt_table_body {
  border-top-style: solid;
  border-top-width: 2px;
  border-top-color: #D3D3D3;
  border-bottom-style: solid;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
}

#lpzwjsibiv .gt_footnotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lpzwjsibiv .gt_footnote {
  margin: 0px;
  font-size: 90%;
  padding-left: 4px;
  padding-right: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lpzwjsibiv .gt_sourcenotes {
  color: #333333;
  background-color: #FFFFFF;
  border-bottom-style: none;
  border-bottom-width: 2px;
  border-bottom-color: #D3D3D3;
  border-left-style: none;
  border-left-width: 2px;
  border-left-color: #D3D3D3;
  border-right-style: none;
  border-right-width: 2px;
  border-right-color: #D3D3D3;
}

#lpzwjsibiv .gt_sourcenote {
  font-size: 90%;
  padding-top: 4px;
  padding-bottom: 4px;
  padding-left: 5px;
  padding-right: 5px;
}

#lpzwjsibiv .gt_left {
  text-align: left;
}

#lpzwjsibiv .gt_center {
  text-align: center;
}

#lpzwjsibiv .gt_right {
  text-align: right;
  font-variant-numeric: tabular-nums;
}

#lpzwjsibiv .gt_font_normal {
  font-weight: normal;
}

#lpzwjsibiv .gt_font_bold {
  font-weight: bold;
}

#lpzwjsibiv .gt_font_italic {
  font-style: italic;
}

#lpzwjsibiv .gt_super {
  font-size: 65%;
}

#lpzwjsibiv .gt_two_val_uncert {
  display: inline-block;
  line-height: 1em;
  text-align: right;
  font-size: 60%;
  vertical-align: -0.25em;
  margin-left: 0.1em;
}

#lpzwjsibiv .gt_footnote_marks {
  font-style: italic;
  font-weight: normal;
  font-size: 75%;
  vertical-align: 0.4em;
}

#lpzwjsibiv .gt_asterisk {
  font-size: 100%;
  vertical-align: 0;
}

#lpzwjsibiv .gt_slash_mark {
  font-size: 0.7em;
  line-height: 0.7em;
  vertical-align: 0.15em;
}

#lpzwjsibiv .gt_fraction_numerator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: 0.45em;
}

#lpzwjsibiv .gt_fraction_denominator {
  font-size: 0.6em;
  line-height: 0.6em;
  vertical-align: -0.05em;
}
</style>
<table class="gt_table">
  <thead class="gt_header">
    <tr>
      <th colspan="7" class="gt_heading gt_title gt_font_normal gt_bottom_border" style><em>Fritillaria</em> species in Northwest USA and Southwest Canada</th>
    </tr>
  </thead>
  <thead class="gt_col_headings">
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="2" colspan="1">Species</th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="2">
        <span class="gt_column_spanner">Canada</span>
      </th>
      <th class="gt_center gt_columns_top_border gt_column_spanner_outer" rowspan="1" colspan="4">
        <span class="gt_column_spanner">United States</span>
      </th>
    </tr>
    <tr>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">ABT</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">BRC</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">IDA</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">MNT</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">ORE</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1">WAS</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria affinis</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria atropurpurea</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria camschatcensis</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria eastwoodiae</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria gentneri</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria glauca</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria pudica</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right">X</td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria purdyi</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
    <tr><td class="gt_row gt_left" style="font-style: italic;">Fritillaria recurva</td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right"></td>
<td class="gt_row gt_right">X</td>
<td class="gt_row gt_right"></td></tr>
  </tbody>
</table>
</div><!--/html_preserve-->

There is a lot more that can be done with `gt` - see https://gt.rstudio.com/ for help, examples and documentation. 



NA
NA
NA
NA
NA
