#' precompile articles that take a long time to run
library(knitr)
library(here)
library(stringr)

# remove the figures folder for regeneration
if (dir.exists(here("vignettes/articles/figure"))) {
  unlink(here("vignettes/articles/figure"), recursive=TRUE)
}

# Find articles to pre-compile
article_root <- here("vignettes/articles")
to_precompile <- list.files(article_root, pattern="Rmd.orig", full.names=TRUE)

# Loop through and pre-compile
for (article in to_precompile) {
  compiled_name <- gsub("\\.orig$", "", article)
  message(paste("Compiling", article))
  knit(article, compiled_name)

  lines <- readLines(compiled_name)
  # remove the annoying 'plot of chunk XXX' auto captions
  lines <- str_replace_all(lines, "(?<=\\!\\[)plot of chunk [a-z0-9\\-]+(?=\\]\\()", "")
  # remove progress bars that print every line
  progress_regex <- "\\#\\> (?:Matching )?=*\\>\\-*\\s+\\d+\\% \\| ETA\\:\\s+\\d+(?:h|m|s)(?: Matching)?\n?"
  lines <- str_replace_all(lines, progress_regex, "REMOVE THIS")
  lines <- str_replace_all(lines, "^\\s+$", "REMOVE THIS")

  lines <- lines[lines != "REMOVE THIS"]
  lines <- c("<!-- GENERATED BY vignettes/articles/precompile.R -->\n", lines)
  writeLines(lines, compiled_name)
}

# move any figures that have been created to the articles folder
file.rename(here("figure"), here("vignettes/articles/figure"))
